import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import { SessionProvider } from "next-auth/react"
import NextAuthProvider from '@/Providers/NextAuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
        <body>
          <NextAuthProvider>
            <Navbar/>
            {children}
          </NextAuthProvider>
        </body>
      </html>
    
  )
}
